/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ProtectedLayoutRouteImport } from './routes/_protectedLayout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProtectedLayoutTableRouteImport } from './routes/_protectedLayout/table'
import { Route as ProtectedLayoutProfileRouteImport } from './routes/_protectedLayout/profile'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ProtectedLayoutTodosTodosRouteImport } from './routes/_protectedLayout/_todos/todos'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutRoute = ProtectedLayoutRouteImport.update({
  id: '/_protectedLayout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutTableRoute = ProtectedLayoutTableRouteImport.update({
  id: '/table',
  path: '/table',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ProtectedLayoutProfileRoute = ProtectedLayoutProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ProtectedLayoutRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtectedLayoutTodosTodosRoute =
  ProtectedLayoutTodosTodosRouteImport.update({
    id: '/_todos/todos',
    path: '/todos',
    getParentRoute: () => ProtectedLayoutRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProtectedLayoutProfileRoute
  '/table': typeof ProtectedLayoutTableRoute
  '/todos': typeof ProtectedLayoutTodosTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProtectedLayoutProfileRoute
  '/table': typeof ProtectedLayoutTableRoute
  '/todos': typeof ProtectedLayoutTodosTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_protectedLayout': typeof ProtectedLayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/_protectedLayout/profile': typeof ProtectedLayoutProfileRoute
  '/_protectedLayout/table': typeof ProtectedLayoutTableRoute
  '/_protectedLayout/_todos/todos': typeof ProtectedLayoutTodosTodosRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/profile' | '/table' | '/todos' | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/profile' | '/table' | '/todos' | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/_protectedLayout'
    | '/login'
    | '/_protectedLayout/profile'
    | '/_protectedLayout/table'
    | '/_protectedLayout/_todos/todos'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProtectedLayoutRoute: typeof ProtectedLayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protectedLayout': {
      id: '/_protectedLayout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ProtectedLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protectedLayout/table': {
      id: '/_protectedLayout/table'
      path: '/table'
      fullPath: '/table'
      preLoaderRoute: typeof ProtectedLayoutTableRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/_protectedLayout/profile': {
      id: '/_protectedLayout/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedLayoutProfileRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_protectedLayout/_todos/todos': {
      id: '/_protectedLayout/_todos/todos'
      path: '/todos'
      fullPath: '/todos'
      preLoaderRoute: typeof ProtectedLayoutTodosTodosRouteImport
      parentRoute: typeof ProtectedLayoutRoute
    }
  }
}

interface ProtectedLayoutRouteChildren {
  ProtectedLayoutProfileRoute: typeof ProtectedLayoutProfileRoute
  ProtectedLayoutTableRoute: typeof ProtectedLayoutTableRoute
  ProtectedLayoutTodosTodosRoute: typeof ProtectedLayoutTodosTodosRoute
}

const ProtectedLayoutRouteChildren: ProtectedLayoutRouteChildren = {
  ProtectedLayoutProfileRoute: ProtectedLayoutProfileRoute,
  ProtectedLayoutTableRoute: ProtectedLayoutTableRoute,
  ProtectedLayoutTodosTodosRoute: ProtectedLayoutTodosTodosRoute,
}

const ProtectedLayoutRouteWithChildren = ProtectedLayoutRoute._addFileChildren(
  ProtectedLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProtectedLayoutRoute: ProtectedLayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
